version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - assets:/app/web/assets
      - runtime:/app/runtime
    ports:
      - '8000:80'
    depends_on:
      -  mysql
    command: ['bash', '/app/docker-php-init.sh']
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 33060:3306
volumes:
  assets:
  runtime: